### ISSUE TITLE
Fix flickering of features in map

### ISSUE THREAD

**Issue by kordilery** [gis4dis/mc-client#14]
Fix flickering of features in map during timeslider changes.

**Comment by kordilery** [comment]
The problem is using ol.style.Icon without any style caching - colaborative task with CG.

**Comment by Bulva** [comment]
Precaching of styles added. But there is a problem with way of calling the generalize function during the animation. We have to use some persistent storage or we have to change the way of calling generalize method (calls only once).

**Comment by Bulva** [comment]
Fixed, issue can be closed.

**Comment by kordilery** [comment]
Closing. Good work, @Bulva . Thanks.
