### ISSUE TITLE
HTTP error 404 for SVG files

### ISSUE THREAD

**Issue by jirik** [gis4dis/mc-client#57]
In console, there are some 404 errors for some SVG files, e.g.:
- /static/symbolization/stream_flow_high_agg.svg
- /static/symbolization/stream_flow_low_agg.svg
- /static/symbolization/precipitation_middle_agg.svg
- /static/symbolization/stream_flow_middle_agg.svg
and probably more

**Comment by jirik** [comment]
@Bulva thanks for the tip
@kordilery please try it

**Comment by kordilery** [comment]
I will check it, but generally it should be automatically copied after [npm install](https://github.com/gis4dis/mc-client/blob/7acacf6698e99f5fd234327c4ed17587b0935647/package.json#L13).

**Comment by kordilery** [comment]
I think it works as it should, closing.
