### ISSUE TITLE
Last observation is sometimes inaccessible

### ISSUE THREAD

**Issue by jirik** [gis4dis/mc-client#68]
See image
https://drive.google.com/file/d/1DYZJChdoVF6jrYHnn5xneDlhMWM_Vsxe/view?usp=sharing
Date 2019-09-30 is available in timeseries, however it's not accessible by date range selector.

Only when default time range is used (when user opens the page or changes aggregation time slots), last date is accessible.

Red caption at "To date" label also shows strange date 2019-09-29, but that's probably another issue.

**Comment by kordilery** [comment]
I think all mentioned bugs are related.

The red caption at "To date" shows 2019-10-29
- it is calculated according to the last version of [documentation](https://github.com/gis4dis/poster/wiki/Interface-between-MC-client-&-MC-server-v2#response-3)
- considering the **value duration**, it probably should be calculated as phenomenon_time_to minus value_duration (in this case 2019-09-30)

In time slider, the **max** value is calculated as
- time of the last observation (previously _phenomenon_time_to - value_frequency_) minus the value_duration, to ensure user cannot reach time without values
- if the last observation calculation will be change to _phenomenon_time_to - value_duration_, the max value can be equal to it

**Comment by jirik** [comment]
About the red caption. It seems either the documentation or the server implementation is wrong, so thanks for pointing. The `phenomenon_time_to` in server response is currently computed probably as "end of the last observation" instead of "beginning of the last observation within feature_collection plus value frequency". This inconsistency then probably causes some of described problems.

Question is, what do you prefer to be in server response. To me the current implementation seems more suitable, however I don't see under the hood of mc-client. If you agree with this, I will fix the documentation.

Another question is, what should be in red captions. In "From Date" it should clearly be the beginning of the first observation, which is the same as phenomenon_time_from in server response. In "To Date", there are three more or less logical options
- beginning of the last observation (currently phenomenon_time_to - value_duration)
- end of the last observation (currently phenomenon_time_to)
- beginning of the last observation within feature_collection plus value frequency (currently phenomenon_time_to - value_duration + value_frequency)

We can discuss this further.

Concerning time slider
- Blue text should show beginning of currently selected time slot represented by the thumb. This works as expected.
- The width of thumb should represent value_duration. This works as expected.
- The first position should represent the first time slot from server response that begins at phenomenon_time_from. This works as expected.
- The last position should represent the last time slot from server response that begins at phenomenon_time_to - value_duration. This is currently broken, as sometimes the last position represents the last-but-one time slot (as it in in the [image](https://drive.google.com/file/d/1DYZJChdoVF6jrYHnn5xneDlhMWM_Vsxe/view?usp=sharing)).

The chart currently works as expected:
- red and blue time line ends at the beginning of the last observation
- horizontal axis ends at the end of the last observation

**Comment by kordilery** [comment]
Ok, if we agreed the `phenomenon_time_to` is the end of the last observation, I can adjust the MC-client to it. I prefer following options:

- **red caption** - beginning of the last observation (`phenomenon_time_to` - `value_duration`)

- **slider** - the last position should represent the last time slot from server response that begins at `phenomenon_time_to` - `value_duration`

Considering the chart, the horizontal axis ends at the end of the last observation, I'm thinking about shortening it just to the beginning of the last observation, as no values are available after the beginning of the last observation. What do you think?
